### ISSUE TITLE
Project partners section into one single section

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#394]
- [x] ```Mockup``` Revamp partners section
- [x] ```DB``` Create new tables and migrate the information 
![20150820_112118](https://cloud.githubusercontent.com/assets/5375915/9410415/ae477d6e-47e5-11e5-9ce6-e6b2a0b88d06.jpg)
 - ProjectPartners, Activities and Deliverable Partnerships
 - Activities
  - leader_id debe apuntar a la tabla project partner_persons
- Deliverables
 - Columna partner_id se debe renombrar partner_person_id y debe apuntar a project_partner_persons

- [x] Adjust history_tables.

- [x] "Validate if there are information already added, manual check"
- [x] ```JAVA``` Create Model
- [x] ```JAVA``` Update Managers (Activities, Deliverables) and validate saving and loading methods
- Project partners manager
 - [x]  getProjectPartner(id): ProjectPartner
 - [x]  getProjectPartners(project): List<projectPartner>
 - [x]  getProjectPartnerByType(project, isPPA): List<projectPartner> --> It was made in the Project object getPPAPartners
 - [x]  saveProjectPatner(projectPartner): int
 - [x]  saveProjectPartners(List<projectPartner>): boolean
 - [x]  deleteProjectPartner(projectPartner): boolean

- Project partner person manager
 - [x] getPartnerPerson(id): PartnerPerson
 - [x] getParnerPersons(ProjectPartner): List<PartnerPerson>
 - [x] saveProjectPartnerPerson(ProjectPartner, PartnerPerson):int
 - [x] saveProjectPartnerPersons(ProjectPartner, List<PartnerPerson>): boolean
 - [x] deleteProjectPartnerPerson(PartnerPerson): boolean
 - [x] Partner person converter

- [x] ```Interface``` 
- [x] ```Validations``` 
![20150828_110101](https://cloud.githubusercontent.com/assets/5375915/9552881/e76dc418-4d80-11e5-9747-1f5ac0e538a7.jpg)
![20150828_114620](https://cloud.githubusercontent.com/assets/5375915/9552883/e9db35aa-4d80-11e5-81a5-e9a5c3b07daa.jpg)
![20150828_121636](https://cloud.githubusercontent.com/assets/5375915/9552884/ecaa8b28-4d80-11e5-8079-a0076e087f48.jpg)

- [x] R1. There must be always a PL.
- [x] R2. PC is not neccesary.
- [x] R3. It is allowed to add partners without contact persons (however it will be required for submitting the project).
- [x] R4. If the project is Bilateral, the intitituion to which the Project Leader belongs must be a PPA.
- [x] R5. If the project is CCAFS-CORE, the institution to wich the Project Leader belongs could be any.
- [x] R6. Responsibility field is optional. (However it will be required for submitting the project).
- [x] R7. MLs (for CCAFS-Core Projects) and CPs (for Bilateral Projects) are able to edit everything in the section.
- [x] R8. PLs wont be able to change the PL.
- [x] R8.1 PC won't be able to change the PL and the PC
- [x] R9. For CCAFS-Core projects, PLs cannot delete and/or add PPA Partners.
- [x] R10. For CCAFS-Core projects, there should be at least one PPA Partner.
- [x] R11. For Bilateral Projects, PLs are able to delete and/or add any PPA Partner.
- [x] R12. PLs can modify the Project Coordinator (PC).
- [x] R13. PLs can modify any Contact Person (CP).

- If a new PL or PC is assigned into the project:
  - [x] R14. Apply permissions to the user on that particular project.
  - [x] R15. Send Email informing what happened:
    - [x] R16. If the PL/PC is new, an email will be sent informing that was assigned as PL/PC for that particular project and the credentials to access to P&R. A password will be randomly generated by the system.
    - [x] R17. If the PL/PC is already exists, an email will be sent information that was assigned as PL/PC for that particular project. (No credentials will be generated as they were generated before).
  - [x] R18. A popup will appear to the ML or CP informing what is going to happen. The user will have to confirm all the process described above.
- If PL or PC is changed:
  - [x] R19. If the PL/PC is in charge of other projects, or if the PL/PC is a MLs or CPs or Admin, then, the permissions to that particular project will be deleted.
  - [x] R20. If the PL/PC  is only working for that particular project, then, the permissions for that particular project will be deleted and the role for that particular user will be modified to Guest.
- [x] R21. There must be only one PL and only one PC.
- [x] R22. Once a partner (institution) is saved, it won't be able to be changed. Instead, the user will have to delete it and add a new one.

Deleting a partner:
- [x] R23. If a partner is deleted, all the contact persons that belong to the partner will be deleted as well.
- [x] R24. If the partner has a PL, a popup will appear indicating that another PL of a different partner need to be selected first.
- [x] R25. If the partner has a PC or just PCs, the partner will be deleted as well as its contact persons.
  - [x] R26. Keep in mind that if the PC is deleted, the system will proceed to do what were indicated in R19 and R20.
- [x] R27. For CCAFS-CORE projects, if the partner is a PPA:
  - Delete deliverable contributions.
  - Delete Budget
  - Delete partner contributions.
  - Popup informing what is going to happen and asking a confirmation before proceed.
- [x] R28. It is not allowed to delete a partner that has is also assigned as Activity Leader.
- [x] R29. If the partner is related to a deliverable, the system allows to delete the partner but a popup will appear indicating what is going to happen (that it will stop contributing to that deliverable).
- [x] R30. An email is sent to the PL/PC informing that he is not a PL/PC any more on that particular project.

**Comment by sebas932** [comment]
There are some validation messages that appear when an action is executed like delete or change, could @htobon or @David help me improving those messages ?

##### Project partner remove action
> **Validate if there are any deliverable linked to any contact person of this partner:**
> _Please bear in mind that if you delete this contact, # deliverables relationswill be deleted_

> **Validate if the CCAFS partner has any contribution to another partner**
> _This partner cannot be deleted due to is currently contributing to another partner_

> **Validate if the project partner has any person as leader role**
> _Please indicate another project leader before deleting this partner._

> **Validate if the user has privileges to remove CCAFS Partners**
> _You don\'t have privileges to delete CCAFS Partners, please contact the ML to delete this partner._

> **Validate if there are any activity linked to any contact person of this partner**
> _This partner cannot be deleted due to is currently related with # activities. _


##### Partner person remove action

> **Validate if the person has any activity related for be changed**
> _This contact cannot be changed due to is currently the Activity Leader for # activity(ies) _


##### Partner person remove action

> **Validate if the person type is PL**
> _Please indicate another project leader before deleting this contact. _

> **Validate if there are any activity linked to this person**
> _This contact cannot be deleted due to is currently the Activity Leader for # activity(ies) _

> **Validate if there are any deliverable linked to this person**
> _Please bear in mind that if you delete this contact, # deliverables relations will be deleted _

Feel free to correct my english
Thank you !

**Comment by davidabreu** [comment]
Project partner remove action
This partner cannot be deleted due to the following reason(s):
Validate if there are any deliverables linked to any contact persons from this partner:
Please bear in mind that if you delete this partner, # deliverables relations will be deleted
Validate if the CCAFS partner is currently contributing has any contributions to another partner

<<The partner>> is currently allocating budget to the following partner(s):
o	 <<partner name>>;
Validate if the project partner has any project leader assigned 
Please indicate another project leader from a different partner before deleting this partner.
Validate if the user has privileges to remove CCAFS Partners
You don\'t have enough privileges to delete CCAFS Partners, please contact the Management Liaison to delete this partner.
Validate if there are any activities linked to any contact persons from this partner
This partner cannot be deleted because at least one or more contact persons is leading the following activity(ies):
Contact person change action
Validate if the person is in charge of any activities
This contact person cannot be changed because he/she is leading the following activity(ies):
Validate if there is another leader selected before
Please be aware that you can only have one project leader per project. Therefore <<the current project leader>> was assigned a contact person role.  
Partner person remove action
Validate if the person type is PL
there must be one project leader per project. Please select another project leader before deleting this contact.
Validate if there are any activities linked to this person
This contact person cannot be deleted because he/she is leading the following activity(ies):
If you want to proceed with the deletion, please go to the following activities and change the activity leader.
Validate if there are any deliverables linked to this person
Please bear in mind that if you delete this contact, # deliverables relations will be deleted.
